use_frameworks!

platform :ios, '8.0'

target 'XQCPodTest_Example' do
  pod 'XQCPodTest', :path => '../'

  target 'XQCPodTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
